typedef   unsigned   long               DWORD; 
typedef   int                                   BOOL; 
typedef   unsigned   char               BYTE; 
typedef   unsigned   short             WORD; 
typedef   float                               FLOAT; 
typedef   FLOAT                               *PFLOAT; 
typedef   bool                        *PBOOL;
typedef   bool                         *LPBOOL;
typedef   BYTE                       *PBYTE;
typedef   BYTE                        *LPBYTE;
typedef   int                            *PINT;
typedef   int                              *LPINT;
typedef   WORD                          *PWORD;
typedef   WORD                            *LPWORD;
typedef   long                            *LPLONG;
typedef   DWORD                        *PDWORD;
typedef   DWORD                          *LPDWORD;
typedef   void                           *LPVOID;
typedef   const   void                *LPCVOID;

typedef   int                                   INT; 
typedef   unsigned   int                 UINT; 
typedef   unsigned   int                 *PUINT;
